#!/usr/bin/env python3
"""Build extract/raw/object_depths.json from the decompiled depth table and generate src/objdata.rs."""
import json, os, re
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
t = open(os.path.join(ROOT, "extract/dump/CodeEntries/gml_GlobalScript___global_object_depths.gml")).read()
d = {int(a): float(b) for a, b in re.findall(r'__objectDepths\[(\d+)\] = (-?[\d.]+)', t)}
n = {int(a): b for a, b in re.findall(r'__objectNames\[(\d+)\] = "([^"]+)"', t)}
depths = {n[i]: d[i] for i in n if i in d}
json.dump(depths, open(os.path.join(ROOT, "extract/raw/object_depths.json"), "w"))
objs = json.load(open(os.path.join(ROOT, "extract/raw/objects.json")))
lines = ["// Generated by tools/object_depths.py from the game's object table. Do not edit.",
         "pub struct ObjInfo { pub sprite: &'static str, pub mask: &'static str, pub parent: &'static str, pub depth: f64, pub visible: bool }",
         "pub fn obj_info(name: &str) -> Option<ObjInfo> {", "    Some(match name {"]
for o, v in sorted(objs.items()):
    lines.append(f'        "{o}" => ObjInfo {{ sprite: "{v["sprite"]}", mask: "{v["mask"]}", parent: "{v["parent"]}", depth: {depths.get(o, 0.0)!r}, visible: {"true" if v["visible"] else "false"} }},')
lines += ["        _ => return None,", "    })", "}"]
open(os.path.join(ROOT, "src/objdata.rs"), "w").write("\n".join(lines) + "\n")
